#!/bin/bash

# installing node (ubuntu example)
add-apt-repository ppa:chris-lea/node.js
apt-get install nodejs=0.10.9-1chl1~precise1

# installing unit testing framework
npm install nodeunit -g

# installing yamd (https://github.com/rystsov/yamd)
npm install https://github.com/rystsov/yamd/raw/master/target/yamd.tar.gz
