// Generated by CoffeeScript 1.6.3
var adds, bind, clear, driver, handlers, items;

bind = rx.bind;

rxt.importTags();

adds = 0;

handlers = rx.cell(0);

driver = rx.cell(0);

items = rx.array();

clear = function(list) {
  var _results;
  _results = [];
  while (list.raw().length !== 0) {
    _results.push(list.remove(list.raw()[0]));
  }
  return _results;
};

$(function() {
  return $('.coffee').prepend(div([
    div(bind(function() {
      return ["Number of subscriptions to 'driver': " + (handlers.get())];
    })), div([
      button({
        click: function() {
          driver.set(driver.get() + 1);
          return handlers.set(driver.onSet.subs.length);
        }
      }, "inc"), button({
        click: function() {
          var item, offset;
          offset = adds++;
          item = bind(function() {
            return driver.get() + offset;
          });
          items.push(item);
          return handlers.set(driver.onSet.subs.length);
        }
      }, "add"), button({
        click: function() {
          clear(items);
          return handlers.set(driver.onSet.subs.length);
        }
      }, "clear"), div(items.map(function(item) {
        return div(bind(function() {
          return ["" + (item.get())];
        }));
      }))
    ])
  ]));
});
