// Generated by CoffeeScript 1.6.3
var alice, bind, bob, history, snapshot;

bind = rx.bind;

rxt.importTags();

alice = rx.cell(10);

bob = rx.cell(15);

history = rx.array();

snapshot = bind(function() {
  return JSON.stringify({
    Alice: alice.get() + "$",
    Bob: bob.get() + "$",
    sum: (alice.get() + bob.get()) + "$"
  });
});

snapshot.onSet.sub(function(_arg) {
  var old, val;
  old = _arg[0], val = _arg[1];
  return history.push(val);
});

$(function() {
  var parcel;
  return $('.coffee').prepend(div([
    div([
      div({
        "class": "accounts-title"
      }, [div([b("Alice's account")]), div([b("Bob's account")])]), div({
        "class": "accounts-value"
      }, [
        div([
          span(bind(function() {
            return [alice.get() + "$"];
          }))
        ]), div([
          span(bind(function() {
            return [bob.get() + "$"];
          }))
        ])
      ]), div({
        "class": "clear"
      })
    ]), div({
      "class": "transfer"
    }, [
      parcel = input({
        "type": "text",
        "value": "2"
      }), button({
        click: function() {
          alice.set(alice.get() - parseInt(parcel.val()));
          return bob.set(bob.get() + parseInt(parcel.val()));
        }
      }, "Transfer from Alice to Bob")
    ]), div({
      "class": "history"
    }, [
      div([b("Account history")]), div({
        "class": "snapshots"
      }, history.map(function(item) {
        return div(item);
      }))
    ])
  ]));
});
